### ISSUE TITLE
When to preprint your exciting paper?

### ISSUE THREAD

**Issue by Aluooooo** [qianyuzqy/IADG#1]
I believe your work is exciting. 
May I ask if your paper can be made public in advance? 
This will be a major boost to the FAS community.
Best wishes.

**Comment by qianyuzqy** [comment]
Hi, @Aluooooo,
Thanks for your interest.
As per your request, we have uploaded our paper to Arxiv, and it will be available this week.

Best wishes,

**Comment by Aluooooo** [comment]
Thank you for your timely response and contribution to FAS.
Have a good day~
