### ISSUE TITLE
code

### ISSUE THREAD

**Issue by Masofish** [qianyuzqy/IADG#2]
Dear author

Congratulations on your work being accepted by CVPR. I would like to inquire further. When will the complete code be released?

**Comment by laiyingxin2** [comment]
when the code will be realeased

**Comment by Garsonjw** [comment]
when the code will be realeased

**Comment by YMLLG** [comment]
when the code will be realeased

**Comment by laiyingxin2** [comment]
when the code will be realeased

**Comment by mlourencoeb** [comment]
I start to think that this a fake research paper. I tried to replicate I have not come close to the reported results.

**Comment by BluebirdStory** [comment]
@mlourencoeb same bro, very likely to be a fake paper.

**Comment by qianyuzqy** [comment]
Hi,  @Masofish @mlourencoeb @YMLLG @laiyingxin2 @Garsonjw 

Sorry for the late reply. 

We have released all our source code and pre-trained models on: https://github.com/qianyuzqy/IADG.
Note that all of our results are real and reproducible. All the code, pre-training models, training logs, and test logs have been released.

Please don't jump to irresponsible conclusions without any evidence.

We hope our paper and code will be helpful for your further research. Thanks for your interest in our work.
If you have any questions, feel free to pull a request to an issue in our Github repository.

Best Regards,
