### ISSUE TITLE
Fail to reproduce

### ISSUE THREAD

**Issue by BluebirdStory** [qianyuzqy/IADG#3]
Strictly reimplement the code according to the paper. Fail to reproduce, a huge gap with the results in the paper.

**Comment by BluebirdStory** [comment]
Actually I am a little mad, do you guys fake?

**Comment by qianyuzqy** [comment]
@BluebirdStory 

Sorry for the late reply. 

We have released all our source code and pre-trained models on: https://github.com/qianyuzqy/IADG.
Note that all of our results are real and reproducible. All the code, pre-training models, training logs, and test logs have been released.

Please don't jump to irresponsible conclusions without any evidence.

We hope our paper and code will be helpful for your further research. Thanks for your interest in our work.
If you have any questions, feel free to pull a request to an issue in our Github repository.

Best Regards,
