### ISSUE TITLE
Checkpoint download not working

### ISSUE THREAD

**Issue by ahernandez900** [qianyuzqy/IADG#5]
Hello. I am trying to download the checkpoint from Baidu to reproduce your results but it seems that the password is not working. Could you please check or upload the files to an alternative location such as Google Drive? Many thanks.

**Comment by qianyuzqy** [comment]
Hi, @ahernandez900 

Thanks for your interest in our work.

As requested, we have uploaded the pre-trained models to the following Google Drive link:

https://drive.google.com/drive/folders/15QjIXXbatQmXzwtR7pydsB4Jqscm7Vb6?usp=sharing

Best Regards,
